apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{  .Values.api.name  }}
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      name: {{  .Values.api.name  }}
  template:
    metadata:
      labels:
        name: {{  .Values.api.name  }}
    spec:
      containers:
        - name: {{  .Values.api.name  }}
          command:
            - "/bin/sh"
            - "-c"
          args:
            - "./entrypoint.sh"
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag | default .Chart.AppVersion }}"
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          volumeMounts:
          - name: envvars
            mountPath: /weather-plants-docker/app/.env
            subPath: .env
      volumes:
        - name: envvars
          configMap:
            name: envvars
