version: '3'

tasks:
  install:
    cmds:
      - helm upgrade --install -f '{{.USER_WORKING_DIR}}'/values.yml weather-plants-helm $PROJECT_ROOT/helm/
    silent: true
  uninstall:
    cmds:
      - helm uninstall weather-plants-helm
    silent: true