apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJYnppSUF1NWU3RkV3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TkRBNE1UQXdPRFExTkRoYUZ3MHpOREE0TURnd09EVXdORGhhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUM0RExwVkpxZG9qaWx1c3VmTkM5bHhDZlY0MHhNK1B3WlB3elh1Qlg2UmlGbFBXa0d2NTNQaWdBVjYKYVUzYUlCQ1dTNE91V1l4RGZiSnE3d2pQNmpJeHZyTEVLdzh1TzFKdTJaZ1VlWDdBTzk0V1NKK0RXc2Vwa2x4TwphREtGTUUvbUlrRUZMRnlxTm5zU0M4MzlvbXZuLzNhb2VTQjJrcWlObTBndFNlL1RzQVQ0V2M4cGpvYXdFdm5kClFxaWk2WjRZOUovQ1RHdzZxT2JFbG9tTzFIUVdzZzJITFJNMVFlLzZMM1J6aG9oSGhrMGNmbnVtcGZtWkM3cm4KZE1rdUdHL2dPSTFIZnYrelh1WmRIS3NBUnZ5emcwVjBhUHhTZmtuQ1FLM3EwK1YxTGpDUmZlc1hOdnhKaTFtSQp3K3QrR3UzL3RES3ZDY0pScDhyeFRWenZ2d2hwQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJSSk8wSHJuNGFhaWZpby9OK0ZocEdjdFBERDREQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQkIzUnVXb1ZXbApVanJHa2JJSVkrVjFUSTV3Yzl4c2hsb25tUGFLZC9mTUlaeHcySTJFeXpXbzcyVDVHZ2FvMkJpYmpMUGNiSUxxCkRabGNGdCtIUmhqbnFJWWNmaWVZTFVEQU54eG1OdWpxT1RON01Sa203N28vYTYxN1VXZlhvZmRuRlZiTUV5YksKRnBXWWNWU2hHMjVRRnlKR2x2cnFPVDVuRmIwQWkycEtROGtlY2JjbnRuaUVSdG1COW14dW5vUnVnSFZzcGkwOQpCSEYzYlZxMlFvc01iSWx1RVJ4K211UGtVZlJsTjd4OGwydjRZYUdFaVpPc1VMUnFaOWFQcytXejZDUEExZENQCjZFbk5razFOeVR0MU9Ja0k3QUM1Y3NqQjExejFNY0FlUnhXdm9rNis4TGV4NEV0V3FEaVNvT25CSkVFWlFrQ2oKQmlQTW1aQjA4QkVyCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://9F364A6791431666A25F2C367D9AC7C1.gr7.eu-west-1.eks.amazonaws.com
  name: arn:aws:eks:eu-west-1:403313062530:cluster/weather-plants
contexts:
- context:
    cluster: arn:aws:eks:eu-west-1:403313062530:cluster/weather-plants
    user: arn:aws:eks:eu-west-1:403313062530:cluster/weather-plants
  name: arn:aws:eks:eu-west-1:403313062530:cluster/weather-plants
current-context: arn:aws:eks:eu-west-1:403313062530:cluster/weather-plants
kind: Config
preferences: {}
users:
- name: arn:aws:eks:eu-west-1:403313062530:cluster/weather-plants
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - eu-west-1
      - eks
      - get-token
      - --cluster-name
      - weather-plants
      - --output
      - json
      command: aws